### ISSUE TITLE
Some questions about your solution

### ISSUE THREAD

**Issue by 4n93L** [Rabbit-Company/Passky-Server#24]
Hello, I have some questions about your solution :

- About encrypting :
When you encrypt the message, it's done by the hash of the password, the same that he is store in the db, so if someone could access to the DB, wouldn't he decrypt passwords stored?

- about geoloc
You use geolocalisation to encrypt password, so what about a user who is travelling, coun't decrypt his passwords ?
Thanks, I love to try to understand that code

**Comment by zigazajc007** [comment]
Hello,

> When you encrypt the message, it's done by the hash of the password, the same that he is store in the db, so if someone could access to the DB, wouldn't he decrypt passwords stored?

![image](https://user-images.githubusercontent.com/44822563/209575903-0d5ccce5-5b0c-447f-a3cb-11cd1f5ff2cc.png)

As you can see in the picture, 2 completely different hashes are generated from your master password. One is used for server authentication (Leaves your device) and another one for password encryption and decryption (Never leaves your device).

> You use geolocalisation to encrypt password, so what about a user who is travelling, coun't decrypt his passwords ?
> Thanks, I love to try to understand that code

This encryption and decryption only happen on the client side and it's used to add another layer of security.

For example:

If someone gets access to your computer while you are logged in to the password manager, he will be able to inspect the elements and steal your data in a localStorage. While all passwords there are encrypted, he can still steal those encrypted passwords and the encrypted hash, so he can use this to decrypt your passwords. So in order to decrypt this hash, an attacker would also need to steal your userAgent / geolocation info in order to decrypt this hash so he can use it to decrypt your passwords.

It's impossible to prevent the attacker from stealing your passwords, if he has access to your computer and you are logged in to your password manager. But in this case we can at least make it "harder" / more time consuming for the attacker.

**Comment by 4n93L** [comment]
Okay that's clear now, but when does XCHACHA20 impact that process ?

**Comment by zigazajc007** [comment]
Argon2id is used for password hashing (One way "encryption"). This means it is technically impossible to get a password from a hash.

While XChaCha20 is used for encryption and decryption. This means we can encrypt your passwords with XChaCha20 and use your hashed master password as secret key.

So everything hashed with Argon2id can't be decrypted and everything encrypted with XChaCha20 can't be decrypted without a secret key.
